
export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS';
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS';