

export const GET_USERS_SUCCESS="GET_USERS_SUCCESS"
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const DELETE_USER_SUCCESS='DELETE_USER_SUCCESS'
export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS'


export const GET_AUTHORIZATIONS_SUCCESS="GET_AUTHORIZATIONS_SUCCESS"
export const CREATE_AUTHORIZATIONS_SUCCESS="CREATE_AUTHORIZATIONS_SUCCESS"
export const UPDATE_AUTHORIZATIONS_SUCCESS="UPDATE_AUTHORIZATIONS_SUCCESS"
export const DELET_AUTHORIZATIONS_SUCCESS='DELET_AUTHORIZATIONS_SUCCESS'